color: null
description: null
fieldLayouts:
  28a61ee0-c680-4781-833a-1201cbcc48a3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-20T20:04:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 23e7a25a-326c-497d-b2d2-8a3f0441478d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98979324-55f3-456b-86a3-5b3bc9a7ab07
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-20T20:04:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b9cc488-3089-4b60-90e7-69f344a260d7 # Excerpt
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 217f76b3-d6a5-40c2-98c6-646803c415fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-20T20:38:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ad8a5f74-72c0-4ba5-8d07-54ab8cea97e8 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c92a7be-07fd-40a6-b185-24333295631a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-20T20:04:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 77e3d49f-4339-4267-8daf-3ba6445ee93e # Featured Image
            handle: backgroundImage
            includeInCards: false
            instructions: null
            label: 'Background Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59632656-217b-46e1-9861-a8a3cabb1fdb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cc0c3aba-99c5-44c1-8537-b7749de14090
        userCondition: null
handle: billboard
hasTitleField: false
icon: image-landscape
name: Billboard
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
