color: null
description: null
fieldLayouts:
  64c693e1-b236-4d5d-9da0-632d0fb396ac:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-19T19:32:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 23e7a25a-326c-497d-b2d2-8a3f0441478d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42499c52-8365-4f95-a407-bfa2735b1723
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-19T19:32:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f3ea580-ece0-4297-b0cd-f62546e76029 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98bfb477-eb1d-4407-8f6d-ea1befc9abe3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5558979e-3801-4761-92b2-8ee4c42f0e3f
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\elements\conditions\entries\FieldConditionRule
              operator: in
              uid: d452732f-a8aa-4ea4-be3a-72bcca6d9bdf
              values:
                - cbed9ff3-3b7b-4fe9-99a3-5773c8920f0b # Content
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            dateAdded: '2025-07-19T19:49:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fd17e42e-291b-4fb6-a3ae-58836dcf9589 # Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adc58fc8-87bc-4aff-9331-7690ec561a88
            userCondition: null
            warning: null
            width: 100
        name: Design
        uid: dbacde88-9ff7-4cdd-a644-a7bb5422ffdf
        userCondition: null
handle: text
hasTitleField: false
icon: paragraph
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heading|default(uid)|striptags}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
