headingLevels:
  - 3
  - 4
  - 5
js: "return {\r\n    alignment: {\r\n        options: [\r\n            'left',\r\n            'center',\r\n            'right',\r\n        ],\r\n    },\r\n    link: {\r\n        decorators: {\r\n            openInNewTab: {\r\n                mode: 'manual',\r\n                label: 'Open in new tab',\r\n                defaultValue: false,\r\n                attributes: {\r\n                    target: '_blank',\r\n                },\r\n            },\r\n            button: {\r\n                mode: 'manual',\r\n                label: 'Button',\r\n                defaultValue: false,\r\n                attributes: {\r\n                    class: 'button button-prose',\r\n                },\r\n            },\r\n        },\r\n    },\r\n    image: {\r\n        toolbar: [\r\n            'imageStyle:wrapText',\r\n            'imageStyle:breakText',\r\n            '|',\r\n            'toggleImageCaption',\r\n            'imageTextAlternative',\r\n            'transformImage',\r\n        ],\r\n        styles: {\r\n            'options': [\r\n                'inline',\r\n                'alignLeft',\r\n                'alignRight',\r\n                'alignCenter',\r\n                'alignBlockLeft',\r\n                'alignBlockRight',\r\n                'block',\r\n                'side',\r\n            ],\r\n        },\r\n    },\r\n}"
name: Standard
toolbar:
  - heading
  - alignment
  - '|'
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
  - insertImage
  - mediaEmbed
  - horizontalLine
  - insertTable
