altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  afcd377d-7842-44d2-8d6a-bb26c67cc9f4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-19T22:17:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e4d4030e-170c-4df7-8f77-af7a78a42ce5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46860ad1-3f99-4acb-a0f1-65a7aaa7f109
        userCondition: null
fs: aws
handle: public
name: Public
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
