columnSuffix: null
handle: background
instructions: null
name: Background
searchable: false
settings:
  default: null
  palette: background
  setRandom: false
  useConfigFile: true
translationKeyFormat: null
translationMethod: none
type: percipiolondon\colourswatches\fields\ColourSwatches
