columnSuffix: null
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels:
    - 3
    - 4
    - 5
  js: "return {\r\n  link: {\r\n    decorators: {\r\n      openInNewTab: {\r\n        mode: 'manual',\r\n        label: 'Open in new tab',\r\n        defaultValue: false,\r\n        attributes: {\r\n          target: '_blank'\r\n        }\r\n      },\r\n    },\r\n  },\r\n}"
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
    - bulletedList
    - numberedList
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
