columnSuffix: null
handle: button
instructions: null
name: Button
searchable: false
settings:
  advancedFields:
    - target
    - urlSuffix
    - ariaLabel
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowedKinds
              -
                - audio
                - captionsSubtitles
                - compressed
                - excel
                - pdf
                - powerpoint
                - text
                - video
                - word
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - asset
    - email
    - tel
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
